### PR TITLE
Don't use MPI constants as compile-time constants

### PR DESCRIPTION
**Pull request by eschnett**
Closes https://github.com/boostorg/mpi/issues/133 .

### CODE REVIEW

**Comment by eschnett** [comment]
Yes. I think I accidentally forgot to create a branch or name it. I didn't spot this until you mentioned it.

**Comment by mkre** [comment]
Hi @aminiussi. Can you please consider merging this PR? We would be interested in having this fix in the upstream version of boost.mpi. Thanks!

**Comment by aminiussi** [comment]
Hi, I'm sorry for the delay.

I need to get up to date with the build and test system. But the change looks ok and It should be merged soon.

**Comment by aminiussi** [comment]
I see that master is closed for the 82.beta at this point.

**Comment by aminiussi** [comment]
But it can still be merged on devlop

**Comment by aminiussi** [comment]
@eschnett for some reason (maybe because it wasn't on a branch) I merged it though the merge button.

I should have use a patch instead:
 
```
/scratch/alainm/view/boostorg/boost/libs/mpi/src/environment.cpp(65): error: identifier "l" is undefined
    switch(l) {
           ^

/scratch/alainm/view/boostorg/boost/libs/mpi/src/environment.cpp(266): error: identifier "int2level" is undefined
    return int2level(level);
           ^

```

was it actually checked ?

I'm going to fix it.

Cheers

**Comment by eschnett** [comment]
Apologies. I am installing Boost via Spack, and it appears that the patch I am applying via Spack is different from the one I used for this PR.

**Pull request merged**
