### PR TITLE
Simple fix of error message when including communicator.hpp and building with nvcc

### PR DESCRIPTION
**Pull request by pkestene**
Ticket #10998 (https://svn.boost.org/trac/boost/ticket/10998) reported a problem which prevents
building any boost::mpi application with compiler nvcc / icc

The error message is :

boost/mpi/communicator.hpp(1750): error: explicit specialization of function "boost::mpi::communicator::send(int, int, const T &) const [with T=boost::mpi::packed_oarchive]" must precede its first use (
(1177): here)

Here is the dummy solution (moving code as the ticket reporter said)

There is probably a better solution.

### CODE REVIEW

**Comment by gnthibault** [comment]
Thank you pkestene, I hope reviewer will integrate your pull request because this aspect is critical for using boost::mpi in cunjunction with nvcc.

**Comment by aminiussi** [comment]
Could you please try to rebase on develop branch ?
I'm having some compilation issue which I will investigate but it could be faster for you.
Thanks

**Comment by aminiussi** [comment]
By the way, I think the compiler is incorrect, what matter is that the _point of instantiation_ for template at line 1177 must be placed after the specialization.

Still, since the issue is with partial specialization declaration (definitions are in communicator.cpp), it could be more elegant to put them just after the class definition.
I'm gonna try that (I do not have easy access to the specified platform but the error message should disappear).

Thanks

**Comment by aminiussi** [comment]
Fixed in #45 thanks a lot and sorry for the delay.

**Pull request closed without merging**
