### PR TITLE
Remove Boost.MPI-specific python-tag code

### PR DESCRIPTION
**Pull request by SoapGentoo**
@pdimov @Lastique

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@pdimov can we merge this?

**Comment by Lastique** [comment]
Could you describe the effect of this change?

**Comment by SoapGentoo** [comment]
to remove the code duplication that is now in central boost build

**Comment by Lastique** [comment]
So there will be no change in the build output?

**Comment by SoapGentoo** [comment]
nope, except that Boost.MPI can now be compield in the presence of multiple python impls

**Comment by Lastique** [comment]
Ok, thanks.

**Comment by pdimov** [comment]
Merging this (or not) is up to MPI's maintainer.

**Pull request merged**
