### PR TITLE
Feature/70p2p opt probe

### PR DESCRIPTION
**Pull request by aminiussi**
This pull request was initially triggered by #63 and #70 and concerns point to point communication involving variable size variable size messages (serialized data, arrays of serialized data, and dynamic array of primitive data).

It basically an optimization. Instead of sending first the size of the message and then the payload, we directly send the payload and uses a call to of of MPI_[M][I]Probe and the receiver side to allocated the receiving buffer.
It fixes the **mpi_any_source** problem mentioned in #63 since we only have one message. 

Note that it won't work with Intel MPI 2018 and older due to a problem in the probe function. So we fall back on the "old" communication in that case.

### CODE REVIEW

**Comment by aminiussi** [comment]
@hirschsn I can't add you to the reviewer list, does this fix your problem ?

**Comment by aminiussi** [comment]
I'd like to merge that soon (by end of the week) so that it can spend as much time as possible in the tests before the next release.

**Comment by Belcourt** [comment]
This appears to be a huge commit.  I can try to review it this weekend, would that work?  Is it possible to reduce the size to something smaller, that would increase the probability of a review?

**Comment by aminiussi** [comment]
This week end would be ok.

I don't think reducing the size is possible, or let's easy enough to be done incrementally by me (I had to maintain the regression testing ok along the way to keep it manageable). Actually, some stuff in the request interface could be improved, but was left out for future work as it would impact non all the wait_* ans test_* code. (deleting the letter/handler once the request is performed, might improve performances, but would require some more changes and thinking w.r.t. request API. So it might be better better left for later too).

The problem is that, due to the intel bug, we need to be able to switch between the non MPI_Probe implementation that use two MPI messages (for size and payload) and the new one (no size message). And the MPI standard now say that we need to be able to mix blocking and non blocking send/recv, so we need to keep all that stuff in sync. That adds a lot of modifications. 

Also, in order to get some flexibility while maintaining backward compatibility (including the possibility to select the implementation at run time, which might be a useful feature for user with "exotic" MPI implementations), I had to implement requests, including the legacy behavior, with the envelop/letter idiom (or kept all the legacy request fields for no reason, which is difficult to justify as requests are used as light weight objects).

And then there was a chicken eggs problem with include files which implied splitting a header (some improvement could be done in this area, but that can be left for later).

One alternative would have been to first provide a "white shot" implementation that would do the same thing but with the letter/envelope, and then add the new request implementation, but due to the above constraints, I'm not sure it would have been that easier (actually, a similar branch spent more than a year waiting for merge and had to be removed eventually, but the changes were not that smaller either).

There are basically two main layer of modifications:

 1. move the request to the letter/envelope idiom. The envelope is the request, which remains a lightweight object, or glorified smart pointer, and the letter is the actual request handler, which derives from "request::handler". Although it does not introduce observable modifications, it's probably the bigger change. I removed the intermediate static handler functions since, although virtual method already implies an indirect, their body can directly do their job with no further indirection. It's big, but mostly a reorganization (these are the "legacy" familly of request handler).
 2. add the new MPI_[M][I]Probe request handler implementation (each request::legacy_XXX class has a functionally equivalent XXX handler based on probes) along this the selection between the tzo implementations.

But yes, it's a big change. Basically the original corner case bug related to any_source is accidentally fixed through a global optimization rewrite (one less message in point to point serialized object transfert).

**Comment by aminiussi** [comment]
> This seems related to the issue @tilsche had reported here:
> 
> https://svn.boost.org/trac10/ticket/12828#no1

It seems to be fixed in that branch, but I don't have an account on the svn tracker.

**Comment by tilsche** [comment]
It looks like this change could in fact fix the linked crash. Thanks for taking a shot at the boost.MPI implementation!

**Comment by aminiussi** [comment]
Thanks, I was away for some time.

So, if I'm not overlooking anything, I need to:
 1. Check documentation and explain what to expect, especially regarding communication progress.
 2 Check automatic feature activation (on by default except for Intel up to 18 included)

regarding 2, my IT is working on the installation of intel19 in order to check that their MPI_Probe bug is fixed on that version.

Thanks!

**Comment by hirschsn** [comment]
Regarding 1: Documenting some internals ("communication progress") is indeed be a good idea. With regard to #72: Maybe a (prominent) section about incompatibilities with the MPI standard could be added to the documentation. (With "prominent" I mean somewhere in the front such that a user might actually be tempted to read it.)

**Pull request merged**
