### PR TITLE
Change partial specialization position to agree with nvcc/icc

### PR DESCRIPTION
**Pull request by aminiussi**
Change partial specialization position to agree with nvcc/icc.
Similar to #44 by @gnthibault and #41 by @pkestene.

### CODE REVIEW

**Comment by aminiussi** [comment]
pass on intel15, checking on g++ 5.2.0 before merging.

**Comment by aminiussi** [comment]
Passed on g++ 5.2.0

**Comment by gnthibault** [comment]
Thank you @aminiussi for the work. Just one question however, I am not familiar with boost testing environment.

When I run b2 inside boost/libs/mpi/test, I just get the following output :

...found 1 target...

Is there something I am doing wrong ?

**Comment by aminiussi** [comment]
That's the number of target you get when mpi is not activated in boost.
In project-config.jam, you should have a 
`using mpi ; # maybe with more options
`
line. Is that the case ?

**Pull request merged**
